<?php
echo "select p_jan = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='01' 
		and substring (start_date,7,4)='2013'),
		p_feb = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='02' 
		and substring (start_date,7,4)='2013'),
		p_mar = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='03' 
		and substring (start_date,7,4)='2013'),
		p_apr = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='04' 
		and substring (start_date,7,4)='2013'),
		p_may = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='05' 
		and substring (start_date,7,4)='2013'),
		p_jun = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='06' 
		and substring (start_date,7,4)='2013'),
		p_jul = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='07' 
		and substring (start_date,7,4)='2013'),
		p_aug = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='08' 
		and substring (start_date,7,4)='2013'),
		p_sep = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='09' 
		and substring (start_date,7,4)='2013'),
		p_oct = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='10' 
		and substring (start_date,7,4)='2013'),
		p_nov = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='11' 
		and substring (start_date,7,4)='2013'),
		p_dec = (select isnull (sum(convert(int, point)),'0') from ppr 
		where division like 'converting%' and substring (start_date,4,2)='12' 
		and substring (start_date,7,4)='2013'),
		np_jan = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='01' 
		and substring (start_date,7,4)='2013'),
		np_feb = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='02' 
		and substring (start_date,7,4)='2013'),
		np_mar = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='03' 
		and substring (start_date,7,4)='2013'),
		np_apr = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='04' 
		and substring (start_date,7,4)='2013'),
		np_may = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='05' 
		and substring (start_date,7,4)='2013'),
		np_jun = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='06' 
		and substring (start_date,7,4)='2013'),
		np_jul = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='07' 
		and substring (start_date,7,4)='2013'),
		np_aug = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='08' 
		and substring (start_date,7,4)='2013'),
		np_sep = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='09' 
		and substring (start_date,7,4)='2013'),
		np_oct = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='10' 
		and substring (start_date,7,4)='2013'),
		np_nov = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='11' 
		and substring (start_date,7,4)='2013'),
		np_dec = (select isnull (sum(convert(int, point)),'0') from nppoint 
		where division like 'converting%' and substring (start_date,4,2)='12' 
		and substring (start_date,7,4)='2013')";
?>