{"ga":[{"sekID":"ws","sek":"Weight Scale"},{"sekID":"gs","sek":"General Services"},{"sekID":"sur","sek":"Surrounding"},{"sekID":"dor","sek":"Dormitory"}],
"isd":[{"sekID":"sec","sek":"Security"},{"sekID":"saf","sek":"Safety"}],
"it":[{"sekID":"hd","sek":"Hardware"},{"sekID":"sw","sek":"Software"}],
"env":[{"sekID":"wwt","sek":"Waste Water Treatment"},{"sekID":"swh","sek":"Solid Water Handling"},{"sekID":"rwt","sek":"Raw Water Treatment"}],
"imh":[{"sekID":"imh","sek":"IKPP Serang Mill Head"},{"sekID":"boi","sek":"Boiler IK Serang"}],
"vpo":[{"sekID":"pfm","sek":"Performance Management"},{"sekID":"pri","sek":"Process Improvement"}],
"hr":[{"sekID":"hro","sek":"HR Operation"},{"sekID":"peo","sek":"People Development"},{"sekID":"er","sek":"Employee Relation"},{"sekID":"rod","sek":"Rec. & Organization Development"}],
"asd":[{"sekID":"pau","sek":"Public Affairs Unit"}],
"pma":[{"sekID":"pas","sek":"PM A Support"},{"sekID":"pm1","sek":"Paper Machine 1"},{"sekID":"pm2","sek":"Paper Machine 2"},{"sekID":"sp1","sek":"Stock Preparation 1"},{"sekID":"pm4","sek":"Paper Machine 4"},{"sekID":"pm5","sek":"Paper Machine 5"},{"sekID":"sk","sek":"Starch Kitchen"}],
"pmb":[{"sekID":"pbs","sek":"PM B Support"},{"sekID":"pm3","sek":"Paper Machine 3"},{"sekID":"pm6","sek":"Paper Machine 6"},{"sekID":"sp2","sek":"Stock Preparation 2"},{"sekID":"ck","sek":"Colour Kitchen"},{"sekID":"ca3","sek":"CaCO3"},{"sekID":"dei","sek":"Deinking"}],
"pfb":[{"sekID":"fbs","sek":"Finishing B Support"},{"sekID":"cub","sek":"Cutting B"},{"sekID":"amb","sek":"AMPS B"}],
"pmc":[{"sekID":"pcs","sek":"PM C Section"},{"sekID":"pm7","sek":"Paper Machine 7"},{"sekID":"sp3","sek":"Stock Preparation 3"}],
"pfc":[{"sekID":"fcs","sek":"Finishing C Support"},{"sekID":"cuc","sek":"Cutting C"},{"sekID":"amp","sek":"Auto & Manual Packing C"}],
"eim":[{"sekID":"ei1","sek":"E&I Maintenance 1 (PMA)"},{"sekID":"ei2","sek":"E&I Maintenance 2 (PMB)"},{"sekID":"ei3","sek":"E&I Maintenance 3 (Utility)"},{"sekID":"ei4","sek":"E&I Maintenance 4 (Converting)"}],
"mam":[{"sekID":"mm1","sek":"Mechanical Maintenance 1 (PMA)"},{"sekID":"mm2","sek":"Mechanical Maintenance 2 (PMB)"},{"sekID":"mm3","sek":"Mechanical Maintenance 3 (Utility)"},{"sekID":"mmm","sek":"Mechanical Maintenance Mobil"},{"sekID":"mm4","sek":"Mechanical Maintenance 4 (Converting)"}],
"man":[{"sekID":"wos","sek":"Workshop Support"},{"sekID":"mac","sek":"Machinery"},{"sekID":"fab","sek":"Fabrication"},{"sekID":"ass","sek":"Assembly"},{"sekID":"pd","sek":"Planning & Design"}],
"prt":[{"sekID":"cvw","sek":"Civil Work"},{"sekID":"pls","sek":"Planning & Supporting"}],
"con":[{"sekID":"ppc","sek":"PPC Unit"},{"sekID":"sbs","sek":"Sub BU Speciality"}],
"crb":[{"sekID":"cr1","sek":"Corrugator 1"},{"sekID":"cpa","sek":"Carton Box Production A"},{"sekID":"cpb","sek":"Carton Box Production B"},{"sekID":"cmw","sek":"Carton Box Manual Work"},{"sekID":"cr2","sek":"Corrugator 2"},{"sekID":"fi1","sek":"Finishing 1"},{"sekID":"fi2","sek":"Finishing 2"},{"sekID":"cbs","sek":"Carton Box Support"},{"sekID":"ptp","sek":"Paper Tube Production"}],
"off":[{"sekID":"ofs","sek":"Offset Support"},{"sekID":"ofp","sek":"Offset Printing"},{"sekID":"of1","sek":"Offset Finishing 1"},{"sekID":"ofm","sek":"Offset Manual Work"},{"sekID":"of2","sek":"Offset Finishing 2"}],
"bs":[{"sekID":"sbp","sek":"Sub BU Packaging"},{"sekID":"sbu","sek":"Sub BU Publishing"},{"sekID":"des","sek":"Design"}],
"fin":[{"sekID":"tpc","sek":"Treasury & Payment Control"},{"sekID":"apv","sek":"AP Verification"},{"sekID":"apv","sek":"General Acc & Taxation"},{"sekID":"sna","sek":"Sales & AR"},{"sekID":"pnr","sek":"Processing & Reporting"},{"sekID":"bnc","sek":"Budget & Costing"}],
"snm":[{"sekID":"sup","sek":"Supporting"},{"sekID":"ppi","sek":"Paper PPIC"}],
"sme":[{"sekID":"sm1","sek":"Sales & Marketing Region 1"},{"sekID":"sm2","sek":"Sales & Marketing Region 2"},{"sekID":"sm3","sek":"Sales & Marketing Region 3"},{"sekID":"sm4","sek":"Sales & Marketing Region 4"},{"sekID":"sm5","sek":"Sales & Marketing Region 5"}],
"mat":[{"sekID":"rmp","sek":"RM Paper & Pulp"},{"sekID":"gms","sek":"General Material Sourcing"},{"sekID":"spe","sek":"Spare Parts Equipment"},{"sekID":"rmc","sek":"RM Chemical"}],
"fin":[{"sekID":"fbg","sek":" F/G Brown Grade WH"},{"sekID":"fwg","sek":" F/G White Grade WH"},{"sekID":"fcg","sek":" F/G Converting WH"}],
"del":[{"sekID":"itr","sek":"Internal Trucking"},{"sekID":"dss","sek":"Delivery Support Section"},{"sekID":"pd","sek":"Paper Delivery"},{"sekID":"cd","sek":"Converting Delivery"}],
"pro":[{"sekID":"pur","sek":"Purchasing"},{"sekID":"lrp","sek":"Local Recycle Paper"},{"sekID":"cna","sek":"Contract & Administration"},{"sekID":"bp","sek":"Bid Packed"}],
"pac":[{"sekID":"wp","sek":"Wood Press"},{"sekID":"son","sek":"Sorting & Recycling"},{"sekID":"plr","sek":"Plastic Recycle"}],
"atl":[{"sekID":"atl","sek":"Asia Trade Logistics"}],
"rdd":[{"sekID":"rdp","sek":"R&D Paper Process"},{"sekID":"rmc","sek":"R&D Material Chemical"},{"sekID":"mrd","sek":"Market Research & Development"}],
"qa":[{"sekID":"qas","sek":"Quality Assurance Support"},{"sekID":"qpa","sek":"QC PM A"},{"sekID":"qpb","sek":"QC PM B"},{"sekID":"qcc","sek":"QC Converting"},{"sekID":"qrm","sek":"QC Raw Material Support"}],
}